### PR TITLE
feat: allow this to be used as a nuxt module 

### PR DESCRIPTION
**Pull request by regenrek**
Hi,

the pr includes the following changes

✅ It's possible to use this repo as nuxt-module in your project
✅ `@vue/composition-api` will be available out of the box
✅ Some minor errors I experience while working with this module

❌ rollup configuration is broken
ℹ️tsc is used to create the build (updated tsconfig)

### CODE REVIEW

**Comment by danielroe** [comment]
@regenrek Great idea. 

Is rollup config still broken for you after https://github.com/danielroe/nuxt-composition-api/commit/849edee610ee536e2755999f878e669019deb363?

**Comment by regenrek** [comment]
Well yes,
your master is already merge into my branch. Some hints here:

```bash
yarn build
yarn run v1.21.1
$ yarn clean && yarn compile
$ rm -rf lib/*
$ rollup -c
(!) You have passed an unrecognized option
Unknown input options: exports. Allowed options: acorn, acornInjectPlugins, cache, context, experimentalCacheExpiry, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveEntrySignatures, preserveModules, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch

src/index.ts → lib/index.js, lib/index.es.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
path (imported by src/index.ts)
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#output-exports
The following entry modules are using named and default exports together:
src/index.ts

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created lib/index.js, lib/index.es.js in 1.2s
✨  Done in 2.05s.
```
And in nuxt
```bash
TypeError: Module should export a function: nuxt-composition-api
```

For this the tsconfig.json has to be originally yours (I changed it so that it works with tsc transpiling (commonjs)

Unfortunately I have less experience with rollup.js so I think rollup needs to be configured that nuxt can find the default export. (Probably because I'm mixing named with default exports)

**Comment by danielroe** [comment]
Got you. 👍

**Comment by danielroe** [comment]
Thanks for the PR! I modified it slightly to fix the build error, but it's still yours 😄

**Comment by regenrek** [comment]
Great. I wanted to get back to this when I'm finished with some other work but I see you did a great job here!

**Pull request closed without merging**
